Develop issue25
ssagara00/rails_app pull request #27
Opened 2023-03-26 07:10 UTC by ssagara00

#25 

画面レイアウト調整。
フロントテスト実装。

レビューのため、作業途中でコミット

2023-03-28 23:38 UTC, yuki-b4 requested changes
確認お願いします！

2023-03-28 23:38 UTC, yuki-b4 commented on react/react-app/src/components/posts/PostsTop.tsx
> +    const changeActive = () => {console.log('ddd')
不要であれば`console.log`削除ください！

2023-03-28 23:38 UTC, yuki-b4 commented on react/react-app/src/components/posts/PostsTop.tsx
> +              <h1 className="text-neutral-content">ようこそ! {currentUser?.name}さん！</h1>
[IMO]
上でログインしているかどうかの条件分岐が行われているので、?.nameは要らないかなと思うのですが、どうですか？

2023-03-28 23:38 UTC, yuki-b4 commented on react/react-app/src/components/posts/PostsTop.tsx
> +              <h1 className="text-neutral-content">ようこそ! {currentUser?.name}さん！</h1>
参考
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2023-03-28 23:38 UTC, yuki-b4 commented on react/react-app/src/components/posts/PostsTop.tsx
> +              <h1 className="text-neutral-content">ようこそ! {currentUser?.name}さん！</h1>
他にも同じような処理をしているところがありそうなので確認ください！

2023-03-28 23:38 UTC, yuki-b4 commented on react/react-app/src/components/posts/Item.tsx
[FYO]
コードとしては問題ないかなと思います！
あくまで提案ベースですが、setLoadingが重複して書かれていたため、少しなんとかできないかと思って調べてみたところ、
https://zenn.dev/t_keshi/articles/attack-on-react-query
で結構良さげなリファクタをしている記事を見つけたので、共有しておきます！

2023-03-28 23:38 UTC, yuki-b4 commented on react/react-app/src/components/users/AuthTop.tsx
tsx拡張子のファイル全体で、`;`はつけるかつけないか、統一した方が良いと思います！

2023-03-28 23:38 UTC, yuki-b4 commented on react/react-app/src/components/users/AuthTop.tsx
> +            console.log("Succeeded in sign out");
不要であれば削除ください！

2023-03-28 23:38 UTC, yuki-b4 commented on react/react-app/src/components/users/AuthTop.tsx
> +            console.log("Failed in sign out");
不要であれば削除ください！

2023-03-30 07:40 UTC, ssagara00 commented
各ファイル大幅に修正しました。

・不要なconsole.logを削除（原則処理失敗時のみ出力）
・reactで、不要な「？」を削除。また、引数がundefinedの場合はエラーを返し、処理を行わないように変更
・setLoadingは、結果的にItem.tsxから記述を削除しました。動作が想定通りにいかなかったためです。
・eslintにセミコロンにかかわるルールを追加。rubocopとeslintでコード整形を実施。

2023-03-30 15:07 UTC, yuki-b4 reviewed
お願いします！

2023-03-30 15:07 UTC, yuki-b4 commented on app/controllers/likes_controller.rb
> +    # @like = Like.find(params[:id])
不要だったら削除で！

2023-03-30 15:07 UTC, yuki-b4 commented on react/react-app/src/components/posts/Detail.tsx
> +          post.image?.url ?
ここ三項演算子ではなく、`post.image?.url`だけで書けませんか？

2023-04-01 16:41 UTC, merged

2023-04-01 16:43 UTC, ssagara00 commented
#25 Closed