fixed likeFunction
ssagara00/rails_app pull request #7
Opened 2023-02-09 02:38 UTC by ssagara00

修正しました。

・削除時、パラメータなしの場合は処理を実行せず早期リターンする。
・flg→my_liked

2023-02-09 23:39 UTC, yuki-b4 requested changes
確認お願いします！

2023-02-09 23:39 UTC, yuki-b4 commented on app/controllers/likes_controller.rb
> +    my_liked = Like.exists?(user_id: params[:user_id], post_id: params[:post_id])
変数名はis_liked?にしましょう！
メソッド名にmyが含まれているのですが、どういうことを表現しようとしていますか？場合によっては`is_liked`だけでも良いのかなと

2023-02-09 23:39 UTC, yuki-b4 commented on app/controllers/likes_controller.rb
> +    if @delLike.nil?
この書き方自体は問題ないのですが、`delLike`って何かの略ですか？
プログラミングにおいては変数名をなるべく省略しないことがよしとされています！

2023-02-11 07:12 UTC, ssagara00 commented
全て修正しました。

・delLike→delete_like
・is_my_likes→is_liked

2023-02-11 07:12 UTC, merged

2023-02-11 07:16 UTC, ssagara00 commented
Closes #6